// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: sample.proto

package sample

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileStreamer_SendFile_FullMethodName = "/sample.FileStreamer/SendFile"
)

// FileStreamerClient is the client API for FileStreamer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileStreamerClient interface {
	SendFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileData, ServerResponse], error)
}

type fileStreamerClient struct {
	cc grpc.ClientConnInterface
}

func NewFileStreamerClient(cc grpc.ClientConnInterface) FileStreamerClient {
	return &fileStreamerClient{cc}
}

func (c *fileStreamerClient) SendFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileData, ServerResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FileStreamer_ServiceDesc.Streams[0], FileStreamer_SendFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileData, ServerResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileStreamer_SendFileClient = grpc.ClientStreamingClient[FileData, ServerResponse]

// FileStreamerServer is the server API for FileStreamer service.
// All implementations must embed UnimplementedFileStreamerServer
// for forward compatibility.
type FileStreamerServer interface {
	SendFile(grpc.ClientStreamingServer[FileData, ServerResponse]) error
	mustEmbedUnimplementedFileStreamerServer()
}

// UnimplementedFileStreamerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileStreamerServer struct{}

func (UnimplementedFileStreamerServer) SendFile(grpc.ClientStreamingServer[FileData, ServerResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SendFile not implemented")
}
func (UnimplementedFileStreamerServer) mustEmbedUnimplementedFileStreamerServer() {}
func (UnimplementedFileStreamerServer) testEmbeddedByValue()                      {}

// UnsafeFileStreamerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileStreamerServer will
// result in compilation errors.
type UnsafeFileStreamerServer interface {
	mustEmbedUnimplementedFileStreamerServer()
}

func RegisterFileStreamerServer(s grpc.ServiceRegistrar, srv FileStreamerServer) {
	// If the following call pancis, it indicates UnimplementedFileStreamerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileStreamer_ServiceDesc, srv)
}

func _FileStreamer_SendFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileStreamerServer).SendFile(&grpc.GenericServerStream[FileData, ServerResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileStreamer_SendFileServer = grpc.ClientStreamingServer[FileData, ServerResponse]

// FileStreamer_ServiceDesc is the grpc.ServiceDesc for FileStreamer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileStreamer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sample.FileStreamer",
	HandlerType: (*FileStreamerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendFile",
			Handler:       _FileStreamer_SendFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "sample.proto",
}
